apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: extensions-postconfigure
data:
  postconfigure.sh: |-
    ### Log that the script started to '/tmp/postconfigure.log'

    echo -e "\n# Executing /opt/eap/extensions/postconfigure.sh... #\n" > /tmp/postconfigure.log

    ### Calling 'jboss-cli.sh' with the configuration contained in 'actions.cli'

    $JBOSS_HOME/bin/jboss-cli.sh --file=/opt/eap/extensions/actions.cli 2>&1 >> /tmp/postconfigure.log

    ### Log that the script has ended to '/tmp/postconfigure.log'

    echo -e "\n# Finished executing /opt/eap/extensions/postconfigure.sh #" >> /tmp/postconfigure.log
